server:
  port: ${PORT}

spring:
  devtools:
    restart: 
      enabled: true
      exclude: static/**,public
    livereload:
      enabled: true

  datasource: 
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DRIVER}
    url: ${DB_URL}

  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      format-sql: true

# My Configs
MY_CONFIG:
  SECRET_KEY: ${SECRET_KEY}