server:
  port: ${PORT}

spring:
  devtools:
    restart: 
      enabled: true
      exclude: static/**,public
    livereload:
      enabled: true

  datasource: 
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DRIVER}
    url: ${DB_URL}

  jpa: 
    show-sql: true
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create-drop
        format-sql: true

